# Generated by Django 4.0.4 on 2023-08-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0002_alter_servicerequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Submitted', max_length=20),
        ),
    ]
