# Generated by Django 4.0.4 on 2023-08-12 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0003_alter_servicerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_balance',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\d{0,9}$')]),
        ),
    ]
