# Generated by Django 4.0.4 on 2023-08-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0007_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Resolved', 'Resolved')], default='Submitted', max_length=20),
        ),
    ]
