# Generated by Django 4.0.4 on 2023-08-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0008_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
