# Generated by Django 4.0.4 on 2023-08-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0009_alter_servicerequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'customer')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
