# Generated by Django 4.0.4 on 2023-08-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0010_customer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
    ]
