# Generated by Django 4.0.4 on 2023-08-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0012_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
