# Generated by Django 4.0.4 on 2023-08-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0013_rename_sender_message_message_remove_message_is_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='sender',
        ),
    ]
