# Generated by Django 4.0.4 on 2023-08-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0014_rename_message_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_request', to='gas_service_app.customer'),
        ),
    ]
