# Generated by Django 4.0.4 on 2023-08-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0016_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
