# Generated by Django 4.0.4 on 2023-08-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0018_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('Power Failure', 'Power Failure'), ('Pole - Shock', 'Pole - Shock'), ('Theft Related Complaint', 'Theft Related Complaint')], max_length=100),
        ),
    ]
