# Generated by Django 4.0.4 on 2023-08-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0020_alter_servicerequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='related_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_messages', to='gas_service_app.servicerequest'),
            preserve_default=False,
        ),
    ]
