# Generated by Django 4.0.4 on 2023-10-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0022_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('Power Failure', 'Power Failure'), ('Power Theft', 'Power Theft'), ('Billing', 'Billing')], max_length=100),
        ),
    ]
