# Generated by Django 4.0.4 on 2023-10-22 18:03
from django.db import migrations
from django.contrib.auth.models import Group

def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name='customer')
    Group.objects.get_or_create(name='support')

class Migration(migrations.Migration):

    dependencies = [
        ('gas_service_app', '0025_alter_servicerequest_request_type'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
