# Generated by Django 4.0.4 on 2023-08-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportTicket',
        ),
    ]
