# Generated by Django 4.0.4 on 2023-08-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_supportr_delete_customer_sr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportR',
        ),
    ]
